### PR TITLE
ci(bhtk): added rebase workflow

### PR DESCRIPTION
**Pull request by BhautikChudasama**
### Changes
- Remove flow trigger from PR.
- Disable image push from any branch.
- Added `/rebase` workflow (https://github.com/cirrus-actions/rebase) 👀.

### CODE REVIEW

**Comment by BhautikChudasama** [comment]
#### Suggestions
* You can add https://probot.github.io/apps/semantic-pull-requests/ for follow convention commit check, So that benefits us in the release.
* You can also add PR size labeling (https://github.com/apps/pull-request-size), when more than one PR it helps us to determine the size of PR.

Thanks.

**Comment by nabsul** [comment]
Hi @BhautikChudasama,

Thank you so much for your contribution. However, I'm going to have to pass on this proposal:

- I want to push images from branches because it allows me to try test versions without a release.
- For the rebase workflow:
  - I prefer to stay in practice by rebasing "the hard way".
  - I don't know `cirrus-actions/rebase@1.5` and feel uncomfortable passing it my `GITHUB_TOKEN`.
 
Still, thank you very much for sharing!

**Comment by BhautikChudasama** [comment]
Thanks @nabsul :)

**Pull request closed without merging**
